version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: your_secure_password
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh admin --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  ubuntu:
    image: ubuntu:22.04
    container_name: ubuntu22
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: sleep infinity
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data: